### ISSUE TITLE
make test causes Segmentation fault.

### ISSUE THREAD

**Issue by ghenry** [brettsheffield/gladd#48]
https://github.com/brettsheffield/gladd/blob/master/src/xml_test.c#L106 causes the issue, which is in turn caused by 

https://github.com/brettsheffield/gladd/blob/master/src/xml.c#L235

and http_get_header not being checked for NULL before strdup https://github.com/brettsheffield/gladd/blob/master/src/xml.c#L238

adding https://github.com/brettsheffield/gladd/blob/master/src/xml.c#L236
                assert(host != NULL);
to confirm.

I've added this to xml_test.c and "make test" now passes, but xml.c should be looked at I reckon.

    ghenry@hodor:~/src/gladbooks/gladd/src$ git diff
    diff --git a/src/xml_test.c b/src/xml_test.c
    index b47fd72..415e603 100644
    --- a/src/xml_test.c
    +++ b/src/xml_test.c
    @@ -99,8 +99,12 @@ char *test_xml_to_sql()
     char *test_xml_replacevars()
     {
             char *sql;
    +        keyval_t *h = NULL;
     
             request = http_init_request();
    +        h = http_set_keyval("Host", "localhost:3000");
    +        request->headers = h;
    +
             asprintf(&request->res, "/myinstance/mybusiness/collection/element");
             asprintf(&sql, "SELECT * FROM $1.$0.myview");
             replacevars(&sql, request->res);

**Comment by ghenry** [comment]
ALL TESTS PASSED
Tests run: 261

**Comment by brettsheffield** [comment]
Hey Gavin,

Many thanks for the bug report.  This is next on my list to look at.  There were a few tests that were failing, and I've been working my way through them when I've had time.  I just hooked the project up to Travis last week and have been cleaning up the code.

Brett
